### ISSUE TITLE
list_stock_tickers() hangs

### ISSUE THREAD

**Issue by odiephd** [hydrosquall/tiingo-python#190] opened 2018-11-19 19:48 UTC
* Tiingo Python version: 0.8
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description

Trying out the service.  Everything works well except when I try to retrieve a list of stock tickers.

No error returned, just hangs.  

### What I Did

```
tickers =client.list_stock_tickers()
no crash, no error, just hangs.
```

**Comment by hydrosquall** [comment] 2018-12-15 22:42
Hi @odiephd, apologies for the delay. Sorry to hear that this didn't work for you, but appreciate you taking the time to report an issue.

I just tried out the following steps on a clean virtual environment:

```bash
pip install tiingo
```

followed by doing the following inside a python session:

```python
from tiingo import TiingoClient
client = TiingoClient() # I authorized my API key using an environment variable
tickers = client.list_stock_tickers()
# //tickers now contains a list of tickers for me to work with.
```

Under the hood, this command is making an internet request, so interruptions to one's wifi or internet connection might make the method hang.

Can you try this again when you get the chance, and let me know if the issue persists? If it does, I should look into making this method a little bit more verbose so we can diagnose what sort of issue might be affecting us.

**Comment by odiephd** [comment] 2018-12-18 16:04
Hi Cameron,

I don't remember exactly what I sent you.  But, I just tried my code 
again and it works fine with retrieving historical data, but hangs when 
I try to get a list of tickers.  The only reason I am looking at the 
list of tickers is I want to know if you have SPX (not SPY)???

Thanks
Jim


------ Original Message ------

**Comment by hydrosquall** [comment] 2018-12-21 21:21
Hi Jim,

I'm not sure why that code snippet isn't working for you, it works out on my end. What happens if the "print" statement gets moved to after the "elapsed time" statement? I can look more at this later, but one possibility is that this large file is taking a very long time to flush to the console.

In any event, it doesn't look like `SPX` is currently one of the supported tickers. You can find the zipfile containing supported tickers at this location in the meantime: 

https://apimedia.tiingo.com/docs/tiingo/daily/supported_tickers.zip

**Comment by hydrosquall** [comment] 2019-01-27 04:43
Feel free to re-open this issue if you have further questions, but I'll close this for now.

**Closed by hydrosquall** 2019-01-27 04:43 UTC

**Comment by Wafaa014** [comment] 2021-09-30 13:53
[https://apimedia.tiingo.com/docs/tiingo/daily/supported_tickers.zip](https://apimedia.tiingo.com/docs/tiingo/daily/supported_tickers.zip) this link is not working for me when trying to open it. \
And also, when running this code:

`
from tiingo import TiingoClient
client = TiingoClient({'api_key': "<my_key>"})
tickers = client.list_stock_tickers()`

I get the following error:

`SSLError: HTTPSConnectionPool(host='apimedia.tiingo.com', port=443): Max retries exceeded with url: /docs/tiingo/daily/supported_tickers.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))`

any ideas on how to solve this?

**Comment by hydrosquall** [comment] 2021-09-30 23:57
@Wafaa014 are you connected to the internet through a proxy server? From putting `Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'` into a search engine, it seems like that could cause this issue (so it's not directly related to tiingo). 

https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

The solution seems to vary by device. I know the address is working without a proxy server, as I was able to open https://apimedia.tiingo.com/docs/tiingo/daily/supported_tickers.zip just now.

**Comment by Wafaa014** [comment] 2021-10-01 10:29
@hydrosquall thank you for the response, I tried it again today and it is working fine!
so it is one of two cases, either there was a problem with the API yesterday, or I had internet issues. I wasn't connected through a proxy server though!
anyways, thanks for the help!
